### PR TITLE
Query

### PR DESCRIPTION
**Pull request by andypasso**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Good job team 
Nice work on this project. Bur before merging to master we need to make some changes to be in line with Microverse guidelines. They are:

- [x] Your navbar must have the TNW logo (unless in the larger breakpoint)

- [x] It's best practice to use the main tag for the most important content of your page.

- [x] The Latest News section must have all articles inside an article tag each.

- [x] In the original page, the Latest News section in 768 ~1024 breakpoint displays 3 items per row:
image

You used 4 in your project. Microverse guidelines require the same approach of the original page. This will make your page look better.

- [x] Since the purpose of this project is responsiveness, Microverse guidelines require that your page looks responsive at least in all sizes between these 3 breakpoints. 

Your page:
image

Original page:
image

- [x] Latest Funding section must have all articles inside an article tag each.

- [x] Apps section must have all articles(8) inside an article tag each.

- [x]  The Latest Deals section in 768 ~1024 breakpoint must displays 3 items per row

kindly make these changes and submit for code review again.

**Comment by Oghenebrume50** [comment]
Hi guys good work so far, but we need to make some changes,  the content in the **latest news**  and the **latest funding rounds** sections are not properly spaced on big screens please fix that. For now everything is fine. Submit for re-review when you are done

**Comment by samgaco** [comment]
### Hi @AndresFMoya and @andynarf :hand: 
### Since all the things pointed by the previous review have been covered and your project looks good, you are approved and can move on :+1: 

* [Suggestions before merging] **Lastest funding rounds** and **latest news** could have a bigger separation between them. 

* [Suggestions before merging] There could be more spacing after the la**test deals** section for the small screen size

**Pull request merged**
